### PR TITLE
Add Eventbrite fetcher

### PR DESCRIPTION
**Pull request by evacchi**
Work in progress. ~~Need to figure out how to pull secrets from config and how to convert fields. It's already sort of working if the API key is hardcoded. I can get the short description for the event in the expected format. I fear getting the full description requires doing another fetch. Not sure if it's worth.~~

- requires `eventbrite-access-token` to be set to a valid token in `.cuttlefishrc`
- It's working although I don't have a full example to test yet (we haven't published the venue for our first meeting because reasons). 
- I can confirm that full description requires a full fetch of a different endpoint  
  https://www.eventbrite.it/platform/api#/reference/event/retrieve-an-event 
  >  Note: If the Event being retrieved was created using the new version of Create, then you may notice that the Event’s description field is now being used to hold the event summary. To retrieve your event’s fully-rendered HTML description, you will need to make an additional API call to retrieve the Event's full HTML description.
- responses are ["paginated"](https://www.eventbrite.it/platform/api#/introduction/paginated-responses) it means that a response may not contain all of the events. There are ways to fix this:
    - set `page_size` to a higher number (?) default is 50
    - set `time_filter` to "last N months" or "last year"
    - set `order_by` to `start_desc`

### CODE REVIEW

**Comment by evacchi** [comment]
I realized that the endpoint `/v3/organizations/$ORGANIZATION_ID/events/`would require a different API token to be given for each chapter, which is suboptimal. 

Now, there *is* an alternative API:
` /v3/events/search/?organizer.id=$ORGANIZER_ID` where $ORGANIZER_ID != $ORGANIZATION_ID

Now I am pretty sure I am doing everything right yet when I do this from cuttlefish/simple-http I get a completely different response from what I get by `curl`ing the same URI. I am very puzzled. `simple-http` gives a listing of what seems to be *all* the events that are active, as if the `organizer.id` parameter were not set. **however** if I print to screen the URI that `simple-http` concatenates I can actually browse to it and get only my organization, as expected. 

Any idea?

**Comment by DarrenN** [comment]
Its looking pretty good - do you have a test response from Eventbrite we could pass to the worker function?

**Comment by evacchi** [comment]
here's a response when no query parameters are given (so full page, 50 items)
https://gist.github.com/evacchi/c7c0fd45d29a1ee8fc6a53ebe3bd2014

**Comment by evacchi** [comment]
:tada:

**Pull request merged**
