### PR TITLE
Add github fetcher

### PR DESCRIPTION
**Pull request by evacchi**
- workflow: users push /data/event.json in the cuttlefish format to their github repo
  - a chapters.json section is added; e.g.:

```json
      "another-city": {
         "dataService": {
              "id": "github-user-id/repo-name",
              "adapter": "github"
          },
          "title": "My City"
       }
```

   e.g. `evacchi/static-test` points to my user repo `static-test`;
   this could often be `papers-we-love/chapter-id`
  - `raw.githubusercontent.com/github-user-id/repo-name/master/data/event.json`
    is fetched and basically used as-is because it is already in the expected format
  - note: this patch is actually using `raw.githack.com` instead of
    `raw.githubusercontent.com` because I could not figure out how to allow
    the text/plain content-type instead of the expected application/json -- because I am a racket n00b

for an example, see https://github.com/evacchi/static-test/

### CODE REVIEW

**Comment by DarrenN** [comment]
I went ahead and merged in the version with tests that I pushed to your fork.

**Comment by evacchi** [comment]
thanks for merging the Eventbrite worker! this is actually a different worker, it takes a GitHub repo and it fetches a JSON that's expected to be already the correct format. That could be a way for Chapters using none of the supported worker to publish the event in a consumable format.

**Comment by DarrenN** [comment]
Ah okay - let's keep working on this one then

**Comment by evacchi** [comment]
hey @DarrenN not sure what happened but this magically gone green. Not sure you want to merge it though

**Pull request closed without merging**
